# -*- coding: utf-8 -*-
"""APPP

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SbaBoPUO8FNY_PihSpRMVbX9ooVpS8xl
"""



from openai import OpenAI
import os
from dotenv import load_dotenv
import base64
import streamlit as st

# Load environment variables from a .env file
load_dotenv()

# Get the OpenAI API key from environment variables
api_key = os.getenv("openai_api_key")

# Initialize the OpenAI client
client = OpenAI(api_key=api_key)

def get_answer(messages):
    """
    Gets a response from the OpenAI chat model.

    Args:
        messages (list): A list of message dictionaries in the format expected by the OpenAI API.

    Returns:
        str: The content of the assistant's message.
    """
    system_message = [{"role": "system", "content": "You are an helpful AI chatbot, that answers questions asked by User."}]
    messages = system_message + messages
    response = client.chat.completions.create(
        model="gpt-3.5-turbo-1106",  # Use a suitable model
        messages=messages
    )
    return response.choices[0].message.content

def speech_to_text(audio_data):
    """
    Converts audio data to text using OpenAI's Whisper model.

    Args:
        audio_data (str): The path to the audio file.

    Returns:
        str: The transcribed text.
    """
    with open(audio_data, "rb") as audio_file:
        transcript = client.audio.transcriptions.create(
            model="whisper-1",
            response_format="text",
            file=audio_file
        )
    return transcript

def text_to_speech(input_text):
    """
    Converts text to speech using OpenAI's TTS model.

    Args:
        input_text (str): The text to convert to speech.

    Returns:
        str: The path to the generated audio file (MP3 format).
    """
    response = client.audio.speech.create(
        model="tts-1",  # Use a suitable TTS model
        voice="nova",   # Choose a voice
        input=input_text
    )
    webm_file_path = "temp_audio_play.mp3" # Changed to mp3
    with open(webm_file_path, "wb") as f:
        response.stream_to_file(webm_file_path)
    return webm_file_path

def autoplay_audio(file_path: str):
    """
    Autoplays an audio file in a Streamlit application.

    Args:
        file_path (str): The path to the audio file (MP3 format).
    """
    with open(file_path, "rb") as f:
        data = f.read()
    b64 = base64.b64encode(data).decode("utf-8")
    md = f"""
    <audio autoplay="true">
    <source src="data:audio/mp3;base64,{b64}" type="audio/mp3">
    </audio>
    """
    st.markdown(md, unsafe_allow_html=True)
